#!/bin/sh

###########################################################################
pgrep -x sxhkd > /dev/null || sxhkd &
#feh --bg-fill ~/.config/bg/linux.jpg &
conky -c $HOME/.conky/.conkyrc &
nitrogen --restore &
numlockx & picom & dunst & mpd &
$HOME/.config/polybar/launch.sh &




###########################################################################
#bspc monitor -d 1 2 3 4 5 6 7 8 9 10
bspc monitor -d '' '' '' '' '' '' '' '' '' ''


###########################################################################
bspc rule -a kitty                desktop='^1' 
bspc rule -a firefox           desktop='^2' follow=on focus=on state=pseudo_tiled
bspc rule -a thunar 	     desktop='^3' follow=on focus=on
bspc rule -a Code 		       desktop='^4' state=floating follow=on focus=on
bspc rule -a vlc 	               desktop='^5' state=floating follow=on focus=on
bspc rule -a gimp 	           desktop='^6' follow=on focus=on
bspc rule -a whatsapp 	           desktop='^7' follow=on focus=on
bspc rule -a telegram 	           desktop='^8' follow=on focus=on
bspc rule -a twitter 	           desktop='^9' follow=on focus=on



###########################################################################
bspc config border_width                1
bspc config window_gap                  5
bspc config top_padding                 0
bspc config left_padding                 2
bspc config right_padding               2

bspc config bottom_padding              1
bspc config normal_border_color          "#ff9800"
bspc config focused_border_color        "#3393dd"
bspc config active_border_color            "#ffffff"
bspc config split_ratio                 0.50

bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config top_monocle_padding         0
bspc config right_monocle_padding       0
bspc config bottom_monocle_padding      0

bspc config left_monocle_padding        0
bspc config single_monocle              false
bspc config focus_follows_pointer       true
bspc config ignore_ewmh_focus           false
bspc config center_pseudo_tiled         true

bspc config honor_size_hints            false
bspc config remove_disabled_monitors    true
bspc config remove_unplugged_monitors   true

###########################################################################
wmname LG3D
export _JAVA_AWT_WM_NONREPARENTING=1